// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © loxx

//@version=5
indicator("[Adapted] Larry Williams Proxy Index (LWPI) [Loxx]", 
     shorttitle="[Adapted] LWPI [Loxx]", 
     overlay = false, 
     timeframe="", 
     timeframe_gaps = true)
    
length = input.int(8, "Period", group = "Basic Settings")

ma = ta.ema(open - close, length)
atr = ta.atr(length)

//LWPI = 50 + (50 * (MA(Open - Close, n) / MA(Range, n)))
lwpi = 50 + (50 * ma / atr)

plot(lwpi, color = color.purple, linewidth = 1)

hline(50, color=color.gray, title = "50", linestyle=hline.style_dashed,linewidth=1, editable=false)

upperbound = input.int(100, "Upper Bound", minval=0, maxval=100)
lowerbound = input.int(0, "Lower Bound", minval=0, maxval=100)

hline(upperbound, color=color.gray, title = "Lower Bound", linestyle=hline.style_dashed,linewidth=1, editable=false)
hline(lowerbound, color=color.gray, title = "Upper Bound", linestyle=hline.style_dashed,linewidth=1, editable=false)

bgcolor(lwpi >= upperbound ? color.rgb(0, 255, 0, 60) : na)
bgcolor(lwpi <= lowerbound ? color.rgb(255, 0, 0, 60) : na)
